//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingtoneManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RingtoneManager.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is devoted to S.D..
        /// </summary>
        public static string AboutDevoted {
            get {
                return ResourceManager.GetString("AboutDevoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is provided &quot;AS IS&quot; without any warranties. Author isn&apos;t responsible for any damage caused by application usage.
        /// </summary>
        public static string AboutNotice {
            get {
                return ResourceManager.GetString("AboutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, note:.
        /// </summary>
        public static string AboutPleaseNote {
            get {
                return ResourceManager.GetString("AboutPleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to ringtone list.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to list.
        /// </summary>
        public static string AddToListButton {
            get {
                return ResourceManager.GetString("AddToListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringtone Manager.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &quot;{0}&quot;.
        /// </summary>
        public static string BusyState {
            get {
                return ResourceManager.GetString("BusyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &quot;{0}&quot;.
        /// </summary>
        public static string BusyStateOnlyAdd {
            get {
                return ResourceManager.GetString("BusyStateOnlyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a part of a song you would like to use..
        /// </summary>
        public static string CutSongWarning {
            get {
                return ResourceManager.GetString("CutSongWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by song title:.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any song yet. If you continue, previously selected song will be set..
        /// </summary>
        public static string FromSettingsWarning {
            get {
                return ResourceManager.GetString("FromSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading song list....
        /// </summary>
        public static string LoadingList {
            get {
                return ResourceManager.GetString("LoadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New art attached..
        /// </summary>
        public static string MediaAttachDone {
            get {
                return ResourceManager.GetString("MediaAttachDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to attach art to your music collection? This process will remove all existing music art images..
        /// </summary>
        public static string MediaAttachWarning {
            get {
                return ResourceManager.GetString("MediaAttachWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files available for media background attaching. Put files called &lt;Band name&gt;.jpg to \MediaAttach\ to enable this option..
        /// </summary>
        public static string NoFilesAvailable {
            get {
                return ResourceManager.GetString("NoFilesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have root access set up for this application. You can do this by using Fully Unlocked ROMs, Root Manager or WP7 Root Tools.
        /// </summary>
        public static string NoRootAccess {
            get {
                return ResourceManager.GetString("NoRootAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zune is currently playing a song started not by Ringtone Manager. If you continue, playlist will be reset..
        /// </summary>
        public static string PlayerIsAlreadyWorking {
            get {
                return ResourceManager.GetString("PlayerIsAlreadyWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set as ringtone.
        /// </summary>
        public static string SetAsRingtoneButton {
            get {
                return ResourceManager.GetString("SetAsRingtoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song has just been added to ringtone list..
        /// </summary>
        public static string SongAdded {
            get {
                return ResourceManager.GetString("SongAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song has just been set as a ringtone..
        /// </summary>
        public static string SongSetAsRingtone {
            get {
                return ResourceManager.GetString("SongSetAsRingtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start position: .
        /// </summary>
        public static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE A RINGTONE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song format is unsupported. However, you still can set it as ringtone or add it to ringtone list..
        /// </summary>
        public static string UnsupportedFormat {
            get {
                return ResourceManager.GetString("UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
